coverage_service: cobertura_xml
xcodeproj: SwiftyJSONAccelerator.xcodeproj
scheme: SwiftyJSONAccelerator
output_directory: build/slather/
workspace: SwiftyJSONAccelerator.xcworkspace
ignore:
  - Pods/*
  - SwiftyJSONAccelerator/UI/External-Libraries/*
