language: swift

osx_image: xcode10.2
xcode_workspace: SwiftyJSONAccelerator.xcworkspace
xcode_scheme: SwiftyJSONAccelerator
xcode_sdk: macosx10.14

before_install:
  - gem install xcpretty
  - gem install slather
  - gem install cocoapods
  - gem install xcov

addons:
  homebrew:
    packages:
    - swiftlint
    - swiftformat
    update: true

script:
  - xcodebuild -workspace SwiftyJSONAccelerator.xcworkspace -scheme "SwiftyJSONAccelerator" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f build/slather/cobertura.xml -X coveragepy -X gcov -X xcode
  - xcov -w SwiftyJSONAccelerator.xcworkspace -s SwiftyJSONAccelerator -o build/xcov --coveralls_service_name travis-ci --coveralls_service_job_id $TRAVIS_JOB_ID
